### ISSUE TITLE
nexus 5X 8.1.0

### ISSUE THREAD

**Issue by zhuhonglei** [xiaokanghub/Frida-Android-unpack#3]
直接返回:Function not exist!
是不支持8.1.0的缘故吗?

**Comment by xiaokanghub** [comment]
https://github.com/xiaokanghub/Frida-Android-unpack/blob/78fa091651184f646bb307fbe1b90138ba383513/dupDex.js#L18  你需要更改一下这里的函数名  或者将下面的判断移除

**Comment by Simp1er** [comment]
我用N5X 8.1.0 试了 不需要改，很完美的脱壳
