### ISSUE TITLE
有的app无法成功

### ISSUE THREAD

**Issue by adamin1990** [xiaokanghub/Frida-Android-unpack#4]
`Spawning `com.rytong.hnair`...
module function name: _ZN3art7DexFile10OpenCommonEPKhmRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEjPKNS_10OatDexFileEbbPS9_PNS0_12VerifyResultE
=========================================
Hook Start
Spawned `com.rytong.hnair`. Resuming main thread!
[Xiaomi MI 5s::com.rytong.hnair]-> base: 0x6bd0b0
size: -820082448
Finished!!!
Error: access violation accessing 0x6bd0b0
    at frida/runtime/core.js:144
    at r (frida/runtime/hexdump.js:7)
    at /dupDex.js:39=========================================

base: 0x746df0
size: -820082448
Finished!!!
Error: access violation accessing 0x746df0
    at frida/runtime/core.js:144
    at r (frida/runtime/hexdump.js:7)
    at /dupDex.js:39=========================================

base: 0x4f0d58
size: -820082448
Finished!!!`

以上是报错信息，壳是360的

**Comment by xiaokanghub** [comment]
方便说一下是什么APP嘛

**Comment by owen800q** [comment]
> 方便说一下是什么APP嘛

@xiaokanghub 我也有这个问题，晋江文学城app
[地址](http://downapk.jjwxc.net/download/android/2/124)

**Comment by owen800q** [comment]
@xiaokanghub

**Comment by xiaokanghub** [comment]
> @xiaokanghub
[Xiaomi MI 8::com.jjwxc.reader]-> base: 0xc6a55000
size: 5528056
           0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
c6a55000  64 65 78 0a 30 33 35 00 88 a5 0b 1e 04 2b 24 1d  dex.035......+$.
c6a55010  50 e0 e7 93 09 22 fd 27 0a 5e 46 cf 25 25 37 7f  P....".'.^F.%%7.
c6a55020  f8 59 54 00 70 00 00 00 78 56 34 12 00 00 00 00  .YT.p...xV4.....
c6a55030  00 00 00 00 70 ed 53 00 a7 83 00 00 70 00 00 00  ....p.S.....p...
magic : dex                                                                                         
035
dex_size :5528056
==============================
木得什么问题啊   应该是你的环境问题

**Comment by owen800q** [comment]
> > @xiaokanghub
> > [Xiaomi MI 8::com.jjwxc.reader]-> base: 0xc6a55000
> > size: 5528056
> > 0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F  0123456789ABCDEF
> > c6a55000  64 65 78 0a 30 33 35 00 88 a5 0b 1e 04 2b 24 1d  dex.035......+$.
> > c6a55010  50 e0 e7 93 09 22 fd 27 0a 5e 46 cf 25 25 37 7f  P....".'.^F.%%7.
> > c6a55020  f8 59 54 00 70 00 00 00 78 56 34 12 00 00 00 00  .YT.p...xV4.....
> > c6a55030  00 00 00 00 70 ed 53 00 a7 83 00 00 70 00 00 00  ....p.S.....p...
> > magic : dex
> > 035
> > dex_size :5528056
> > ==============================
> > 木得什么问题啊   应该是你的环境问题

@xiaokanghub 換雷神模拟器成功le
