### ISSUE TITLE
雷电模拟器hook失败

### ISSUE THREAD

**Issue by owen800q** [xiaokanghub/Frida-Android-unpack#5]
运行脚本后，自动打开追书神器app，弹出这个提示
360的壳
![image](https://user-images.githubusercontent.com/19252045/71539266-94589580-2974-11ea-888e-1fd0c2739b27.png)

**Comment by owen800q** [comment]
@xiaokanghub 点击ok后app是正常运行的。没有闪退，就是hook不出dex，OpenMemory函数是存在的

**Comment by xiaokanghub** [comment]
> @xiaokanghub 点击ok后app是正常运行的。没有闪退，就是hook不出dex，OpenMemory函数是存在的
请在真机环境下脱壳
